// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBneHmsvDkY7cgp8hNGop5zlHHQ9qNF1A0',
    appId: '1:960802526806:web:8d4eece4fac9648208cdf7',
    messagingSenderId: '960802526806',
    projectId: 'msgapp-bbed5',
    authDomain: 'msgapp-bbed5.firebaseapp.com',
    storageBucket: 'msgapp-bbed5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdi7fYAYu7ZMvoenOKzoFe6lkH1j_ds1U',
    appId: '1:960802526806:android:e00a5fb346e93a0d08cdf7',
    messagingSenderId: '960802526806',
    projectId: 'msgapp-bbed5',
    storageBucket: 'msgapp-bbed5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBneHmsvDkY7cgp8hNGop5zlHHQ9qNF1A0',
    appId: '1:960802526806:web:2cf881c270dc332f08cdf7',
    messagingSenderId: '960802526806',
    projectId: 'msgapp-bbed5',
    authDomain: 'msgapp-bbed5.firebaseapp.com',
    storageBucket: 'msgapp-bbed5.appspot.com',
  );

}